server:
  port: 8084

spring:
  profiles:
    active: dev
  application:
    name: cgh-image
  servlet:
    multipart:
      # 上传文件总的最大值
      max-request-size: 10MB
      # 单个文件的最大值
      max-file-size: 10MB


